#!/bin/bash
# scripts/setup-secrets.sh — Generate terraform.tfvars from .env + 1Password
# Resolves op:// references to actual values

set -euo pipefail

SCRIPT_DIR="$(dirname "$0")"
PROJECT_DIR="$SCRIPT_DIR/.."
ENV_FILE="$PROJECT_DIR/.env"
TFVARS_FILE="$PROJECT_DIR/terraform/terraform.tfvars"

if [ ! -f "$ENV_FILE" ]; then
  echo "ERROR: .env not found. Copy .env.example to .env first."
  exit 1
fi

# Source .env (handle quoted values with spaces)
set -a
source "$ENV_FILE"
set +a

# Resolve op:// references
resolve_op() {
  local val="$1"
  if [[ "$val" == op://* ]]; then
    op read "$val" 2>/dev/null || echo "RESOLVE_FAILED:$val"
  else
    echo "$val"
  fi
}

AK=$(resolve_op "${HUAWEI_ACCESS_KEY}")
SK=$(resolve_op "${HUAWEI_SECRET_KEY}")
MAAS=$(resolve_op "${MAAS_API_KEY:-}")
DEEPSEEK=$(resolve_op "${DEEPSEEK_API_KEY:-sk-placeholder}")
DWS_PASS=$(resolve_op "${DWS_ADMIN_PASSWORD:-AycoD3mo2026!}")
LANGFUSE_PUBLIC=$(resolve_op "${LANGFUSE_PUBLIC_KEY:-}")
LANGFUSE_SECRET=$(resolve_op "${LANGFUSE_SECRET_KEY:-}")

# Check for critical failures
for name_val in "access_key:$AK" "secret_key:$SK"; do
  name="${name_val%%:*}"
  val="${name_val#*:}"
  if [[ "$val" == RESOLVE_FAILED:* ]]; then
    echo "ERROR: Could not resolve $name from ${val#RESOLVE_FAILED:}"
    echo "  Make sure 1Password CLI is authenticated: op whoami"
    exit 1
  fi
done

cat > "$TFVARS_FILE" << EOF
# Auto-generated by setup-secrets.sh — DO NOT EDIT MANUALLY
# Generated: $(date -Iseconds)

region     = "${HUAWEI_REGION:-la-north-2}"
access_key = "$AK"
secret_key = "$SK"
project_id = "${HUAWEI_PROJECT_ID:-fbb6435c497c41bda90a0cc5240573e0}"

keypair_name       = "${SSH_KEYPAIR_NAME:-hermes-agent}"
presenter_ip       = "${PRESENTER_IP:-0.0.0.0/0}"
dws_admin_password = "$DWS_PASS"
maas_api_key       = "$MAAS"
deepseek_api_key   = "$DEEPSEEK"
langfuse_public_key = "$LANGFUSE_PUBLIC"
langfuse_secret_key = "$LANGFUSE_SECRET"
langfuse_host       = "${LANGFUSE_HOST:-https://cloud.langfuse.com}"
EOF

echo "✓ terraform.tfvars generated (secrets resolved from 1Password)"
echo "  File: $TFVARS_FILE"
echo "  LLM:  MaaS DeepSeek v4 Flash (primary) + DeepSeek direct (fallback)"
echo "  DO NOT commit this file — it contains credentials"
